# Generated by Django 5.1.2 on 2025-04-21 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_requirements'),
        ('quiz', '0009_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='GlobalRanking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='quiz.globalranking'),
        ),
    ]
