# Generated by Django 5.1.3 on 2025-04-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Business', 'Business'), ('Management', 'Management'), ('Law', 'Law'), ('Aptitude', 'Aptitude'), ('Logical', 'Logical'), ('Web Development', 'Web Development'), ('Communication', 'Communication')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topics/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
