# Generated by Django 5.1.3 on 2025-04-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_topic_category_alter_topic_image_alter_topic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Business', 'Business'), ('Management', 'Management'), ('Law', 'Law'), ('Aptitude', 'Aptitude'), ('Logical', 'Logical'), ('Web Development', 'Web Development'), ('Communication', 'Communication')], default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
    ]
