# Generated by Django 5.1.3 on 2025-04-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_category_remove_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Business', 'Business'), ('Management', 'Management'), ('Law', 'Law'), ('Aptitude', 'Aptitude'), ('Logical', 'Logical'), ('Web Development', 'Web Development'), ('Communication', 'Communication')], default='', max_length=50),
        ),
    ]
