# Generated by Django 5.1.3 on 2025-04-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_topic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Business & Management', 'Business & Management'), ('Web Development', 'Web Development'), ('Database Management', 'Database Management'), ('Technical', 'Technical'), ('Law', 'Law'), ('General Test', 'General Test'), ('Other Specialized Area', 'Other Specialized Area')], default='', max_length=50),
        ),
    ]
