# Generated by Django 5.1.2 on 2025-04-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
